CREATE DATABASE Peluqueria_Canina;
USE Peluqueria_Canina;
CREATE TABLE DUEÑO ( 
DNI INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
TELEFONO INT,
DIRECCION VARCHAR(20),
PRIMARY KEY (DNI)
);
CREATE TABLE PERRO (
DNI_DUEÑO INT NOT NULL,
ID_PERRO INT NOT NULL auto_increment,
NOMBRE VARCHAR (20) NOT NULL,
FECHA_DE_NACIMIENTO DATE,
SEXO CHAR NOT NULL,
PRIMARY KEY (ID_PERRO),
FOREIGN KEY (DNI_DUEÑO) REFERENCES DUEÑO (DNI)
);
CREATE TABLE HISTORIAL (
ID_HISTORIAL INT NOT NULL,
ID_PERRO INT,
FECHA DATE,
DESCRIPCION VARCHAR (150),
MONTO INT,
PRIMARY KEY(ID_HISTORIAL),
FOREIGN KEY (ID_PERRO) REFERENCES perro (ID_PERRO) 
);
USE Peluqueria_Canina;
INSERT INTO DUEÑ0 (DNI,NOMBRE,APELLIDO,TELEFONO,DIRECCION) 
VALUES ('33555888','JORGE','PEREZ','223123456','RIVADAVIA 123');
INSERT INTO PERRO (DNI_DUEÑO,ID_PERRO,NOMBRE,FECHA_DE_NACIMIENTO,SEXO)
VALUES ('33555888','1','CHICHO','2020-06-06','M');
--EJERCICIO 7 
SELECT * FROM HISTORIAL WHERE MONTO BETWEEN 2022-07-01 AND 2022-07-31